rbti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rbti_app.urls')),
]

rbti_app/urls.py
from django.urls import path
from .views import *
app_name="rbti_app"
urlpatterns = [
    path('', newhome, name='home'),
    path('peminjaman/<id_buku>',create_peminjaman, name = "create_peminjaman"),
    path('peminjaman/',create_peminjaman, name = "create_peminjaman"),
    path('list_peminjaman/', peminjaman, name = "peminjaman"),
    path('peminjaman/ajax/<npm>',ajax,name="ajax"),
    path('peminjaman/ajax/',ajax,name="ajax")
]

peminjaman/models.py
from django.db import models

# Create your models here.

rbti_app/models.py
from django.db import models

class Buku(models.Model):
    id_buku = models.CharField(primary_key=True, max_length=255)
    judul = models.CharField(null=True,max_length=255)
    penulis = models.CharField(null=True,max_length=255)
    penerbit = models.CharField(null=True,max_length=255)
    tahun = models.CharField(null=True,max_length=255)
    class Meta:
        managed = True
        db_table = 'rbti_app_buku'
    def __str__(self):
        return self.id_buku

class Mahasiswa(models.Model):
    npm = models.BigIntegerField(primary_key=True)
    nama = models.CharField(null=False, max_length=255)
    email = models.CharField(null=True, max_length=255)

class Peminjaman(models.Model):
    tanggal_peminjaman=models.DateField(auto_now_add=True)
    tanggal_pengembalian=models.DateField(null=True)
    npm=models.ForeignKey(Mahasiswa, on_delete=models.CASCADE)
    id_buku=models.ForeignKey(Buku, on_delete=models.CASCADE)

class Admin(models.Model):
    username = models.CharField(max_length=255, primary_key = True)
    password = models.CharField(max_length=255)

rbti_app/forms.py
from django import forms
from django.forms.formsets import formset_factory
from django.forms import widgets

class PeminjamanForm(forms.Form):
    NIM = forms.CharField(max_length=255)
    Id_Buku = forms.CharField(max_length=255)
    Tanggal_Peminjaman = forms.DateField()

peminjaman/views.py
from django.shortcuts import render

# Create your views here.

rbti_app/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import ListView,CreateView
from django.shortcuts import get_object_or_404
from .models import *
from .forms import PeminjamanForm
import datetime
from django.db import connection, DatabaseError, transaction
import json as simplejson
# Create your views here.

def newhome(request):
    Cursor = connection.cursor()
    Cursor.execute("SELECT * FROM rbti_app_buku WHERE id_buku NOT IN (SELECT id_buku_id FROM rbti_app_peminjaman)")
    books = Cursor.fetchall()
    Cursor.execute("SELECT id_buku_id FROM rbti_app_peminjaman")
    no_books = Cursor.fetchall()
    print(no_books)
    args = {
    'books' : books
    }
    return render(request,"rbti_app/newhome.html",args)
# class BukuListView(ListView):
#     model = Buku
#     template_name = 'rbti_app/newhome.html'
#     context_object_name = 'books'
#     ordering = ['id_buku']


# class BukuListViewAlt(ListView):
#     model = Buku
#     template_name = 'rbti_app/home.html'
#     context_object_name = 'books'
#     ordering = ['id_buku']
# class PeminjamanCreateView(CreateView):
#     model = Peminjaman
#     fields = ["id_buku","npm"]
#     def dispatch(self, request, *args, **kwargs):
#         self.id_buku_id = get_object_or_404(Buku, pk=kwargs['id_buku'])
#         print("!!!!!!!!!!!! ID BUKU ADALAH {idbuku} !!!!!!!!!!!!! ".format(idbuku=self.id_buku_id))
#         return super().dispatch(request, *args, **kwargs)
#     def form_valid(self, form):
#         form.instance.id_buku_id=self.id_buku_id
#         form.instance.tanggal_peminjaman=datetime.datetime.now()
#         return super().form_valid(form)
#     def get_context_data(self, **kwargs):
#         data = super(PeminjamanCreateView, self).get_context_data(**kwargs)
#         data['id_buku'] = Buku.objects.get(pk=self.id_buku_id)
#         data['judul'] = Buku.objects.get(pk=self.id_buku_id).judul
#         return data

        # self.id_buku_id = get_object_or_404(Buku, pk=kwargs['id_buku'])
    


def peminjaman(request):
    peminjamans = Peminjaman.objects.all().filter(tanggal_pengembalian__isnull=True)
    print(peminjamans)
    args = {
        'peminjamans' : peminjamans
    }
    return render(request,"rbti_app/peminjaman.html",args)

def create_peminjaman(request,id_buku):
    Cursor = connection.cursor()
    if(request.method == 'POST'):
        nim=request.POST.get("NIM")
        print(nim)
        id_buku_list = request.POST.getlist("id_buku_form")
        last_peminjaman = Peminjaman.objects.last()
        if(last_peminjaman == None):
            id=0
        else:
            id = last_peminjaman.id + 1
        Cursor.execute("INSERT INTO rbti_app_peminjaman VALUES (%s,%s,%s,%s,%s)",[id,datetime.datetime.now(),None,id_buku,nim])
        id += 1
        print(id_buku_list)
        for id_buku_object in id_buku_list:
            try:
                print("ID BUKU : " + id_buku_object)
                current_book = Buku.objects.get(id_buku=id_buku_object)
                Cursor.execute("INSERT INTO rbti_app_peminjaman VALUES (%s,%s,%s,%s,%s)",[id,datetime.datetime.now(),None,id_buku_object,nim])
                id += 1
            except:
                message = "Oops! ID invalid for book {0}".format(id_buku_object)
                args = {
                    'message': message
                }
                return render(request,"rbti_app/peminjaman_form.html",args)
    if(id_buku == "0"):
        return render(request,"rbti_app/peminjaman_form.html")
    else:
        try:
            Cursor.execute("SELECT * FROM rbti_app_buku WHERE id_buku=%s",[id_buku])
            book = Cursor.fetchone()
            if(book == None):
                raise Exception()
            args ={
                'book' : book
            }
        except:
            args ={
                'message' : "Something went wrong! Please try a different book."
            }
        finally:
            return render(request,"rbti_app/peminjaman_form.html",args)
def ajax(request,npm):
    print("MASUK VIEW")
    args={
        'success':True,
    }
    mahasiswa = Mahasiswa.objects.get(npm=npm)
    print("HEYYY " + str(mahasiswa.npm))
    args = {
        str(mahasiswa.npm) +";",
        mahasiswa.nama + ";",
        mahasiswa.email + ";"
    }
    return HttpResponse(args)



    

rbti_app/templates/rbti_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>RBTI</title>
  </head>
  <body>
  <nav class="navbar navbar-light bg-light ">
  <a class="navbar-brand" href="#">EGA JABLAY</a>
</nav>
<main class="container-fluid">
  {% block content %}
  {% endblock  %}
</main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

rbti_app/templates/rbti_app/bikin_peminjaman.html
{% extends 'rbti_app/index.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST" action="">
    {% csrf_token %}
	<!-- <p>NIM</p> {{ form.NIM }}
    <p>Id Buku</p> {{ form.Id_Buku }}
    <p>Tanggal Peminjaman</p> {{ form.Tanggal_Peminjaman}} -->
    {{form|crispy}}
    <button type="submit">Submit</button>

</form>
{% endblock content %}

rbti_app/templates/rbti_app/home.html
{% extends 'rbti_app/base.html' %}
{% block content %}
<div class="border p-2 rounded">
<h2>Koleksi RBTI</h2>
<div class="border p-3 rounded">
<table class="table table-hover" style=margin-top:0.62rem;>
    <thead>
        <tr>
            <th>ID</th>
            <th>Judul</th>
            <th>Penulis</th>
            <th>Penerbit</th>
            <th>Tahun</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td>{{book.id_buku}}</td>
            <td>{{book.judul}}</td>
            <td>{{book.penulis}}</td>
            <td>{{book.penerbit}}</td>
            <td>{{book.tahun}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>
{% endblock  %}

rbti_app/templates/rbti_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design for Bootstrap</title>
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'rbti_app/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'rbti_app/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'rbti_app/css/style.css' %}">
  <!-- MDBootstrap Datatables  -->
  <link href="{% static 'rbti_app/css/addons/datatables2.min.css' %}" rel="stylesheet">
</head>
<body>

  <!-- Start your project here-->
  <nav class="navbar navbar-dark primary-color">
  <a class="navbar-brand" href="#">RBTI Universitas Brawijaya</a>
  </nav>
  <main class=container>
  {% block content %}

  {% endblock  %}
  </main>
  <!-- End your project here-->

  <!-- jQuery -->
  <script type="text/javascript" src="{% static 'rbti_app/js/jquery.min.js' %} "></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'rbti_app/js/popper.min.js' %} "></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'rbti_app/js/bootstrap.min.js' %} "></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'rbti_app/js/mdb.min.js' %} "></script>
  <!-- Your custom scripts (optional) -->
  <script type="text/javascript"></script>
  <!-- MDBootstrap Datatables  -->
  <script type="text/javascript" src="{% static 'rbti_app/js/addons/datatables2.min.js' %}"></script>
  <script>
  $(document).ready(function () {
    $('#dtBasicExample').DataTable();
    $('.dataTables_length').addClass('bs-select');
  });
  </script>

</body>
</html>

rbti_app/templates/rbti_app/newhome.html
{% extends 'rbti_app/index.html' %}
{% block content %}
<div class = "row">
<div class = "col-4">
<div class="card mt-4">
    <ul class="list-group list-group-flush">
      <a href = "{% url 'rbti_app:peminjaman' %}" class="list-group-item">Peminjaman</a>
      <a  class = "list-group-item active">List Buku</a>
    </ul>
  </div>
</div>
<div class="col-8">
<table id="dtBasicExample" class="table table-hover table-sm mt-2 " cellspacing="0" width="100%">
  <thead>
        <tr>
            <th>ID</th>
            <th>Judul</th>
            <th>Penulis</th>
            <th>Penerbit</th>
            <th>Tahun</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
        <tr>
            <td>{{book.0}}</td>
            <td>{{book.1}}</td>
            <td>{{book.2}}</td>
            <td>{{book.3}}</td>
            <td>{{book.4}}</td>
            <td> <a class = "btn" href = "{% url 'rbti_app:create_peminjaman' %}{{book.0}}" class="btn btn-outline-secondary ">Pinjam</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
</div>

<script>
$(document).ready(function () {
   $('#dtBasicExample').DataTable();
   $('.dataTables_length').addClass('bs-select');
});
</script>
{% if message %}
<script>
 alert("{{message}}");
</script>
{% endif %}
{% endblock content %}

rbti_app/templates/rbti_app/peminjaman.html
{% extends 'rbti_app/index.html' %}
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<div class = "row">
    <div class = "col-">
    <div class="card mt-4">
        <ul class="list-group list-group-flush">
          <a class="list-group-item active">Peminjaman</a>
          <a href = "{% url 'rbti_app:home' %}" class = "list-group-item">List Buku</a>
        </ul>
    </div>
      </div>
<div class = "col-8">
<table id="dtBasicExample" class="table table-hover table-sm mt-2 " cellspacing="0" width="100%">
  <thead>
        <tr>
            <th>ID Buku</th>
            <th>Npm Peminjam</th>
            <th>Tanggal Peminjaman</th>
            <th>Tanggal Pengembalian</th>
        </tr>
    </thead>
    <tbody>
        {% for case in peminjamans %}
        <tr>
            <td>{{case.id_buku_id}}</td>
            <td>{{case.npm.npm}}</td>
            <td>{{case.tanggal_peminjaman}}</td>
            <td>{{case.tanggal_pengembalian}}</td>
            <td><button type=button><a href=#> UPDATE </a></button></td>
        </tr>

        {% endfor %}
    </tbody>
</table>

</div>
<div class = "col-1">
    <a href="{% url 'rbti_app:create_peminjaman' %}{{0}}" class="btn"> Input Peminjaman </a>
</div>
</div>
<script>
$(document).ready(function () {
   $('#dtBasicExample').DataTable();
   $('.dataTables_length').addClass('bs-select');
});
</script>
{% endblock content %}

rbti_app/templates/rbti_app/peminjaman_form.html
{% extends 'rbti_app/index.html' %}
{% block content %}
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
{% if book %}
<h1>Anda akan meminjam buku dengan judul <b>{{book.1}}</b></h1>
{% endif %}
<div id = "detail_mahasiswa">
    <div id="nim_mahasiswa"></div>
    <div id="nama_mahasiswa"></div>
    <div id="email_mahasiswa"></div>
</div>
<form method = 'POST'>
    {% csrf_token %}
    <div class = "form-group col-md-5 nim-handler">
        <label> NIM </label>
        <input class="form-control form-control-sm" rows="1" id = "NIM" name="NIM"> </input>
        <button type="button" id="nim_button">Submit NIM</button>
    </div>
    <div class="form-row"id="id_buku">
        {% if book %}
        <div class="form-group col-md-10 id_buku_select">
            <label>ID Buku</label>
            <input class="form-control form-control-sm" name="id_buku_form" value={{book.0}} disabled> </input>
        </div>
        {% else %}
        <div class="form-group col-md-10 id_buku_select">
            <label>ID Buku</label>
            <input class="form-control form-control-sm" name="id_buku_form">  </input>
        </div>
        {% endif %}
        <div class="form-group col-md-4">
            <button type="button"  id="button_plus_active">+</button>
        </div>
    </div>
    <button type="submit">Submit</button>

</form>
<script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
<script type="text/javascript" src="{% static 'rbti_app/js/peminjaman_form.js' %}"></script>
{% if message %}
<script>
    alert('{{ message }}');
</script>
{% endif %}
{% endblock content %}